# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - iface
    - interfacebloat
    - misspell
    - unconvert
    - unused
    - unparam
    - dupl
    - dupword
    - gocritic
    - gocyclo
    - godox
  exclusions:
    paths:
      - bin
      - dist
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec
  settings:
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - commentFormatting

formatters:
  enable:
    - gofmt
    - goimports
